<a href="https://colab.research.google.com/github/trucnguyen55555/tvdatafeed_Example/blob/main/Ph%C6%B0%C6%A1ng_ph%C3%A1p_3_C%C3%A1ch_l%E1%BA%A5y_d%E1%BB%AF_li%E1%BB%87u_t%E1%BB%AB_Tradingview_b%E1%BA%B1ng_th%C6%B0_vi%E1%BB%87n_Tvdatafeed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Phương pháp 3: Cách lấy dữ liệu từ Tradingview bằng thư viện Tvdatafeed**

# **Giới thiệu**
Tiếp nối 2 phần trước về cách lấy dữ liệu lịch sử từ thị trường chứng khoán Việt Nam bằng [VNQuant](https://www.qmcapital.vn/bai-viet/kien-thuc/kien-thuc-chung/cach-lay-du-lieu-bang-thu-vien-vnquant) và [Vnstock](https://www.qmcapital.vn/bai-viet/kien-thuc/kien-thuc-chung/cach-lay-du-lieu-bang-thu-vien-vnstock). Bài viết này, QM Capital sẽ giới thiệu một phương pháp khác có thể lấy được dữ liệu của các sàn giao dịch trên thế giới từ Tradingview bằng thư viện Tvdatafeed. Cả 3 phương pháp này đều được sử dụng chung trên nền tảng Python qua những dòng code nên việc lấy hết sức dễ dàng và đơn giản, điều này cũng giúp nhà đầu tư tự động hóa quy trình và nhanh chóng. Tvdatafeed là một thư viện Python được thiết kế để giúp người dùng tải xuống dữ liệu lịch sử từ nền tảng TradingView. Với Tvdatafeed, người dùng có thể dễ dàng truy cập và sử dụng dữ liệu lịch sử của các tài sản tài chính như cổ phiếu, tiền điện tử, hoặc chỉ số từ TradingView để phục vụ cho mục đích phân tích kỹ thuật và giao dịch.

**Đặc điểm chính:**
1.   Có thể áp dụng phương pháp này cho tất cả các dữ liệu của chứng khoán thế giới, crypto, commodity index... bằng việc thay Symbol và exchange
2.   Tradingview cung cấp dữ liệu theo nhiều interval khác nhau (phút, giờ, ngày, tuần). Do đó có thể áp dụng trading strategy ở nhiều khung giờ khác nhau.
3. Có thể tải xuống dữ liệu từ nhiều sàn giao dịch khác nhau, bao gồm NASDAQ, NYSE, LSE, NSE, HOSE v.v.


**Hạn chế:**

- Đối với chứng khoán Việt nam: Dữ liệu VNINDEX không có volume! Do Tradingview không cung cấp (kể cả tài khoản premium và mua thêm dữ liệu)

- Chỉ lấy được tối đa 20.000 quan sát tùy thuộc gói Tài khoản của bạn, Gói trả phí có thể nâng lên 25k-30k

[Link bài viết chi tiết của QM Capital](https://www.qmcapital.vn/bai-viet/kien-thuc/kien-thuc-chung/cach-lay-du-lieu-tu-tradingview-bang-thu-vien-tvdatafeed)


*Trên đây là một số đặc điểm chính và hạn chế của phương pháp lấy dữ liệu lịch sử giá từ Tradingview bằng thư viện Tvdatafeed mà QM Capital đã tổng hợp lại. Qua 3 phương pháp, mỗi phương pháp đều có những ưu và nhược điểm riêng, tùy thuộc vào mục đích sử dụng mà nhà đầu tư lựa chọn linh hoạt. Tóm lại, việc lấy dữ liệu sử dụng công cụ Python ngày càng được phổ biến và có nhiều nguồn thư viện mở giúp nhà đầu tư có thể dễ dàng tiếp cận chỉ với những lệnh code đơn giản, từ đó sẽ giúp nhà đầu tư tự động hóa và tăng hiệu suất.*

# **DOWNLOAD DỮ LIỆU LỊCH SỬ GIÁ**

# **Phần I. Cài đặt thư viện**

In [ ]:
# Cài đặt thư viện `vnquant` trực tiếp từ mã nguồn GitHub để sử dụng các tính năng.
!pip install --upgrade --no-cache-dir git+https://github.com/rongardF/tvdatafeed.git

# **Phần II. Đăng nhập tài khoản Tradingview**

In [ ]:
from tvDatafeed import TvDatafeed, Interval

username = 'your username'
password = 'your password'

tv = TvDatafeed(username, password)

# **Phần III. Download dữ liệu lịch sử**

In [ ]:
# Dữ liệu lịch sử của mã chỉ số
vndata = tv.get_hist(symbol='VNINDEX',exchange='HOSE',interval=Interval.in_1_hour,n_bars=1000)
vndata.head()

                           symbol     open     high      low    close  volume
datetime
2023-06-01 06:00:00  HOSE:VNINDEX  1073.10  1075.06  1071.61  1074.23     0.0
2023-06-01 07:00:00  HOSE:VNINDEX  1074.55  1078.39  1074.22  1078.39     0.0
2023-06-02 02:00:00  HOSE:VNINDEX  1084.19  1087.06  1083.36  1085.68     0.0
2023-06-02 03:00:00  HOSE:VNINDEX  1085.78  1090.01  1085.11  1087.47     0.0
2023-06-02 04:00:00  HOSE:VNINDEX  1087.52  1089.68  1087.51  1089.30     0.0

In [ ]:
# Dữ liệu lịch sử của mã chứng khoán
acbdata = tv.get_hist(symbol='ACB',exchange='HOSE',interval=Interval.in_1_hour,n_bars=1000)
acbdata.head()

                       symbol     open     high      low    close     volume
datetime
2023-06-05 04:00:00  HOSE:ACB  21950.0  21950.0  21850.0  21950.0   621900.0
2023-06-05 06:00:00  HOSE:ACB  21950.0  21950.0  21650.0  21800.0  3886500.0
2023-06-05 07:00:00  HOSE:ACB  21800.0  21800.0  21650.0  21750.0  1682000.0
2023-06-06 02:00:00  HOSE:ACB  21800.0  21850.0  21700.0  21700.0  1552500.0
2023-06-06 03:00:00  HOSE:ACB  21700.0  21800.0  21700.0  21750.0   995800.0

In [ ]:
# Dữ liệu lịch sử của chỉ số hàng hóa
commodity_data = tv.get_hist(symbol='CL1!', exchange='NYMEX', interval=Interval.in_1_hour, n_bars=1000)
commodity_data.head()

                         symbol   open   high    low  close   volume
datetime
2024-01-17 16:00:00  NYMEX:CL1!  71.67  72.31  71.60  71.69  19680.0
2024-01-17 17:00:00  NYMEX:CL1!  71.69  72.08  71.52  71.61  10014.0
2024-01-17 18:00:00  NYMEX:CL1!  71.61  72.36  71.55  72.32  11388.0
2024-01-17 19:00:00  NYMEX:CL1!  72.31  72.77  72.30  72.72  17753.0
2024-01-17 20:00:00  NYMEX:CL1!  72.73  72.82  72.66  72.79   3948.0

In [ ]:
# Dữ liệu lịch sử của Crypto
btc_data = tv.get_hist(symbol='BTCUSD', exchange='COINBASE', interval=Interval.in_1_hour, n_bars=1000)
btc_data.head()

,symbol,open,high,low,close,volume
datetime,,,,,,
2024-02-06 13:00:00,COINBASE:BTCUSD,42745.32,42960.93,42697.02,42835.66,216.956201
2024-02-06 14:00:00,COINBASE:BTCUSD,42835.66,43058.34,42770.94,42900.00,435.807234
2024-02-06 15:00:00,COINBASE:BTCUSD,42900.00,43237.82,42861.38,43212.92,758.488661
2024-02-06 16:00:00,COINBASE:BTCUSD,43212.91,43372.79,43135.59,43151.77,1015.348622
2024-02-06 17:00:00,COINBASE:BTCUSD,43148.92,43261.88,43085.76,43170.18,524.962451

# **Phần III. Trực quan hóa dữ liệu**

In [ ]:
# Nhập các thư viện trực quan hóa dữ liệu
import plotly.subplots as ms
import plotly.graph_objects as go

# Tạo subplot với 2 hàng
fig = ms.make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.02)

# Thêm biểu đồ Candlestick cho dữ liệu 'ACB'
fig.add_trace(go.Candlestick(x=acbdata.index,
                             open=acbdata['open'],
                             high=acbdata['high'],
                             low=acbdata['low'],
                             close=acbdata['close'],
                             name='Candlestick'),
              row=1, col=1)

# Thêm biểu đồ Volume dưới dạng cột
fig.add_trace(go.Bar(x=acbdata.index, y=acbdata['volume'], name='Volume'),
              row=2, col=1)

# Cập nhật bố cục của biểu đồ
fig.update_layout(title='ACB Candlestick Chart',
                  yaxis_title='Price',
                  xaxis_title='Date',
                  xaxis_rangeslider_visible=False,
                  bargap=0.3,)  # Khoảng cách giữa các cột Volume

# Hiển thị biểu đồ
fig.show()